Eric Sunshine imported newer crystal.m4 from CS/mk/automake.  Also made minor aesthetic improvements to configure.ac.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -276,7 +276,7 @@ PACKAGE_STRING='cel 0.97'
 PACKAGE_BUGREPORT='cel-main@lists.sourceforge.net'
 
 ac_unique_file="mk/jam/build.jam"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX INSTALL RANLIB ac_ct_RANLIB SWIG CPP CRYSTAL CSCONF PYTHON LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX INSTALL RANLIB ac_ct_RANLIB SWIG CPP CRYSTAL CSCONF ac_ct_CSCONF PYTHON LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1269,7 +1269,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 PACKAGE_LONGNAME="Crystalspace Entity Layer"
-    PACKAGE_COPYRIGHT="(c)2002,2003 Jorrit Tyberghein and others."
+    PACKAGE_COPYRIGHT="(C)2002,2003 Jorrit Tyberghein and others."
     PACKAGE_HOMEPAGE="http://cel.sourceforge.net/"
 
 
@@ -2238,8 +2238,8 @@ fi
 
 
 if test -z "$CC"; then
-  { { echo "$as_me:$LINENO: error: Couldn't find a usable C compiler." >&5
-echo "$as_me: error: Couldn't find a usable C compiler." >&2;}
+  { { echo "$as_me:$LINENO: error: Could not find a usable C compiler." >&5
+echo "$as_me: error: Could not find a usable C compiler." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -2577,8 +2577,8 @@ fi
 
 
 if test -z "$CXX"; then
-  { { echo "$as_me:$LINENO: error: Couldn't find a usable C++ compiler." >&5
-echo "$as_me: error: Couldn't find a usable C++ compiler." >&2;}
+  { { echo "$as_me:$LINENO: error: Could not find a usable C++ compiler." >&5
+echo "$as_me: error: Could not find a usable C++ compiler." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3443,10 +3443,11 @@ fi
 
 if test "x$CRYSTAL" = "x"
 then
-   for ac_prog in cs-config
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+   if test -n "$ac_tool_prefix"; then
+  for ac_prog in cs-config
+  do
+    # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
+set dummy $ac_tool_prefix$ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_CSCONF+set}" = set; then
@@ -3462,7 +3463,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_CSCONF="$ac_prog"
+    ac_cv_prog_CSCONF="$ac_tool_prefix$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -3480,8 +3481,53 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-  test -n "$CSCONF" && break
+    test -n "$CSCONF" && break
+  done
+fi
+if test -z "$CSCONF"; then
+  ac_ct_CSCONF=$CSCONF
+  for ac_prog in cs-config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ac_ct_CSCONF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ac_ct_CSCONF"; then
+  ac_cv_prog_ac_ct_CSCONF="$ac_ct_CSCONF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ac_ct_CSCONF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
 done
+done
+
+fi
+fi
+ac_ct_CSCONF=$ac_cv_prog_ac_ct_CSCONF
+if test -n "$ac_ct_CSCONF"; then
+  echo "$as_me:$LINENO: result: $ac_ct_CSCONF" >&5
+echo "${ECHO_T}$ac_ct_CSCONF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$ac_ct_CSCONF" && break
+done
+
+  CSCONF=$ac_ct_CSCONF
+fi
 
    if test "x$CSCONF" = "x"
    then
@@ -5115,6 +5161,7 @@ s,@SWIG@,$SWIG,;t t
 s,@CPP@,$CPP,;t t
 s,@CRYSTAL@,$CRYSTAL,;t t
 s,@CSCONF@,$CSCONF,;t t
+s,@ac_ct_CSCONF@,$ac_ct_CSCONF,;t t
 s,@PYTHON@,$PYTHON,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
