Eric Sunshine updated Autoconf and Jam utility files from master copies in CS repository.

diff --git a/cel/trunk/configure b/cel/trunk/configure
--- a/cel/trunk/configure
+++ b/cel/trunk/configure
@@ -2319,12 +2319,22 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
     if test -n "$CC"; then
 
-	cs_jamconfig_text="${cs_jamconfig_text}CMD.CC ?= \"$CC\" ;
+	cs_build_prop_val="$CC"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}CMD.CC ?= \"$cs_build_prop_val\" ;
 "
+fi
+
 
 	CFLAGS=`echo "$CFLAGS" | sed 's/\-O.//g;s/\-g.//g'`
-	cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS += \"$CPPFLAGS $CFLAGS\" ;
+	cs_build_prop_val="$CPPFLAGS $CFLAGS"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS += \"$cs_build_prop_val\" ;
 "
+fi
+
 
 fi
 
@@ -2334,6 +2344,7 @@ if test -z "$CC"; then
 echo "$as_me: error: Could not find a usable C compiler." >&2;}
    { (exit 1); exit 1; }; }
 fi
+
 
 
     ac_ext=cc
@@ -2693,12 +2704,184 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
     if test -n "$CXX"; then
 
-	cs_jamconfig_text="${cs_jamconfig_text}CMD.C++ ?= \"$CXX\" ;
+	cs_build_prop_val="$CXX"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}CMD.C++ ?= \"$cs_build_prop_val\" ;
 "
+fi
+
 
         CXXFLAGS=`echo "$CXXFLAGS" | sed 's/\-O.//g;s/-g.//g'`
-	cs_jamconfig_text="${cs_jamconfig_text}COMPILER.C++FLAGS += \"$CPPFLAGS $CXXFLAGS\" ;
+	cs_build_prop_val="$CPPFLAGS $CXXFLAGS"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.C++FLAGS += \"$cs_build_prop_val\" ;
 "
+fi
+
+
+	echo "$as_me:$LINENO: checking if -fPIC is accepted" >&5
+echo $ECHO_N "checking if -fPIC is accepted... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_fpic+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @-fPIC@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_fpic=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+else
+  cs_cv_prog_cxx_fpic=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_fpic" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_fpic" >&6
+    if test "$cs_cv_prog_cxx_fpic" != no; then
+  cs_build_prop_val="$cs_cv_prog_cxx_fpic"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS.PIC ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+
+fi
+
 
 fi
 
@@ -2710,18 +2893,32 @@ echo "$as_me: error: Could not find a usable C++ compiler." >&2;}
 fi
 
 
-
     if test -n "$CXX"; then
-  cs_jamconfig_text="${cs_jamconfig_text}CMD.LINK ?= \"\$(CMD.C++)\" ;
-"
-else
-  cs_jamconfig_text="${cs_jamconfig_text}CMD.LINK ?= \"\$(CMD.CC)\" ;
+  cs_build_prop_val="\$(CMD.C++)"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}CMD.LINK ?= \"$cs_build_prop_val\" ;
 "
 fi
 
-
-    cs_jamconfig_text="${cs_jamconfig_text}COMPILER.LFLAGS += \"$LDFLAGS\" ;
+else
+  cs_build_prop_val="\$(CMD.CC)"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}CMD.LINK ?= \"$cs_build_prop_val\" ;
 "
+fi
+
+fi
+
+
+    cs_build_prop_val="$LDFLAGS"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.LFLAGS += \"$cs_build_prop_val\" ;
+"
+fi
+
 
     echo "$as_me:$LINENO: checking if -shared is accepted" >&5
 echo $ECHO_N "checking if -shared is accepted... $ECHO_C" >&6
@@ -2884,8 +3081,13 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_link_shared" >&5
 echo "${ECHO_T}$cs_cv_prog_link_shared" >&6
     if test "$cs_cv_prog_link_shared" != no; then
-  cs_jamconfig_text="${cs_jamconfig_text}PLUGIN.LFLAGS += \"-shared\" ;
+  cs_build_prop_val="-shared"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PLUGIN.LFLAGS += \"$cs_build_prop_val\" ;
 "
+fi
+
 fi
 
 
@@ -3196,8 +3398,13 @@ echo "${ECHO_T}$cs_cv_prog_link_soname" >&6
 fi
 
     if test $cs_cv_prog_link_soname = yes; then
-  cs_jamconfig_text="${cs_jamconfig_text}PLUGIN.LFLAGS.USE_SONAME ?= \"yes\" ;
+  cs_build_prop_val="yes"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PLUGIN.LFLAGS.USE_SONAME ?= \"$cs_build_prop_val\" ;
 "
+fi
+
 else
   cs_cv_prog_link_soname_cflags=''
 	cs_cv_prog_link_soname_lflags=''
